all:

train:
	mkdir train

none:
	mkdir train/None

inside:
	mkdir train/Bicycle
	mkdir train/Car
	mkdir train/Motorcycle
	mkdir train/Number-plate
	mkdir train/Autorickshaw
	mkdir train/Rickshaw
	mkdir train/Person

delfeatures:
	rm features/*.p

delmodel:
	rm models/*.p

clean:
	rm -rf train/Bicycle
	rm -rf train/Car
	rm -rf train/Motorcycle
	rm -rf train/Number-plate
	rm -rf train/Rickshaw
	rm -rf train/Autorickshaw
	rm -rf train/Person
